In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(arr[0])
print(arr[2])

[1 2 3 4 5]
1
3


In [12]:
arr = np.array([10, 20, 30, 40])

print(arr)

print(arr.ndim)  # Number of dimensions
print(arr.shape)  # Shape of the array          
print(arr.size)   # Total number of elements
print(arr.dtype)  # Data type of the elements

[10 20 30 40]
1
(4,)
4
int64


In [15]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])

print(arr)
print("arr[1, 2] --> ", arr[1, 2])

print(arr.ndim)   # dimensions
print(arr.shape)  # shape
print(arr.size)   # number of elements
print(arr.dtype)  # data type

[[10 20 30 40]
 [50 60 70 80]]
arr[1, 2] -->  70
2
(2, 4)
8
int64


In [ ]:
arr_zero = np.zeros((3, 4))
print(arr_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr_ones = np.ones((2, 3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [18]:
arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

30.0
150
50
10


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [20]:
ran_arr = np.random.randint(1, 100, size=5)
print(ran_arr, "\n")

ran_arr_2d = np.random.rand(3, 4)
print(ran_arr_2d)

[34 99  6 11 58] 

[[0.55950475 0.95184982 0.02033148 0.59088552]
 [0.00667463 0.30230038 0.13079152 0.64522734]
 [0.72067672 0.31800932 0.45390032 0.90439982]]
